- "Enemy critically succeeds save vs spell"
- "PC critically fails death save"
- "Successful skill check with nat 20"
- "Failed skill check with nat 1"
- "Successfully identify magic item"
- "Successfully identify monster"
- "Critical success on recall knowledge"
- "Disease/poison save crit success"
- "Hero point reroll success/fail"
- "Crafting successful magic item"
- "Secret passage found with perception check"
- "Crit Fail by 15+"
- "Crit Succeed by 15+"
- "NPC charmed"
- "Magic item found"
- "Someone rolls a nat 20"
- "Someone rolls a nat 1" 
- "Someone crits on an attack roll"
- "Someone rolls a 1 on a damage die"
- "Someone rolls max on a damage die"
- "Someone fails a saving throw by 5 or more"
- "Someone succeeds on a saving throw by 5 or more"
- "An enemy is killed in one hit"
- "An enemy is immune to a type of damage"
- "An NPC is killed by the party"
- "An NPC joins the party"
- "The party finds a hidden treasure"
- "The party triggers a trap"
- "The party encounters a puzzle"
- "The party solves a puzzle"
- "The party fails to solve a puzzle"
- "The party is ambushed by enemies"
- "The party finds a secret passage"
- "The party is offered a quest"
- "The party completes a quest"
- "The party fails a quest"
- "The party encounters a dragon"
- "The party encounters a giant"
- "The party encounters an undead creature"
- "The party encounters a group of bandits"
- "The party encounters a group of goblins"
- "The party encounters a mimic"
- "The party encounters a group of kobolds"
- "The party encounters a group of skeletons"
- "The party encounters a group of zombies"
- "The party encounters a group of cultists"
- "The party encounters a group of pirates"
- "A PC loses a limb"
- "A PC gains a magical item"
- "A PC is cursed"
- "The party encounters a talking animal"
- "The party encounters a talking plant"
